

#ifndef OUTERMOST_RECTANGLE_H_
#define OUTERMOST_RECTANGLE_H_
#include "../__include.h"

#define DEFAULT_BORDER_CORNER '+'
#define DEFAULT_BORDER_CORNER_DOT '.'
#define DEFAULT_BORDER_VERTICAL '|'
#define DEFAULT_BORDER_HORIZONTAL '-'

// #define OUTERMOST_BORDER_CORNER '+'
// #define OUTERMOST_BORDER_VERTICAL '|'
// #define OUTERMOST_BORDER_HORIZONTAL '-'

#define OUTERMOST_BORDER_ALL_IN_ONE '#'

#define OUTERMOST_BORDER_CORNER  OUTERMOST_BORDER_ALL_IN_ONE
#define OUTERMOST_BORDER_VERTICAL  OUTERMOST_BORDER_ALL_IN_ONE
#define OUTERMOST_BORDER_HORIZONTAL  OUTERMOST_BORDER_ALL_IN_ONE



/*this is outermost top left coordinate*/
#define OUTERMOST_BORDER_X 38
#define OUTERMOST_BORDER_Y 16



/*this is outermost width and height*/
#define OUTERMOST_BORDER_WIDTH 66
#define OUTERMOST_BORDER_HEIGHT 20

/*this is meaning border margin*/
#define MEANING_MIDDLE_MARGIN 5

/*this is T_F meaning margin*/
#define T_F_MEANING_MARGIN 5

/*this is T_F bottom margin*/
#define T_F_BOTTOM_MARGIN 5

/*this is the gap between the middle area and the side function area*/
#define LEFT_MIDDLE_MARGIN 4 
#define RIGHT_MIDDLE_MARGIN LEFT_MIDDLE_MARGIN 
#define TOP_MIDDLE_MARGIN LEFT_MIDDLE_MARGIN 
#define BOTTOM_MIDDLE_MARGIN MEANING_MIDDLE_MARGIN +T_F_BOTTOM_MARGIN+ MARGIN_WORD_BORDER_Y+MARGIN_WORD_BORDER_Y

/*this is _something about left gamelist_are*/
#define GAMELIST_WIDTH 30
#define GAMELIST_HEIGHT TOP_MIDDLE_MARGIN + BOTTOM_MIDDLE_MARGIN + OUTERMOST_BORDER_HEIGHT+TOP_MIDDLE_MARGIN+RIGHT_MIDDLE_MARGIN


/*this is coordinate of all key points*/

/*this is the outermost border's topleft as well as our benchmark*/
#define COORDINATE_MIDDLE_TOP_LEFT_X OUTERMOST_BORDER_X
#define COORDINATE_MIDDLE_TOP_LEFT_Y OUTERMOST_BORDER_Y

/*this is gamelist */

/*this is gamelist topleft*/
#define COORDINATE_GAMELIST_TOP_LEFT_X COORDINATE_MIDDLE_TOP_LEFT_X-LEFT_MIDDLE_MARGIN-GAMELIST_WIDTH
#define COORDINATE_GAMELIST_TOP_LEFT_Y COORDINATE_MIDDLE_TOP_LEFT_Y-RIGHT_MIDDLE_MARGIN-TOP_MIDDLE_MARGIN
/*this is gamelist topright*/
#define COORDINATE_GAMELIST_TOP_RIGHT_X COORDINATE_GAMELIST_TOP_LEFT_X+GAMELIST_WIDTH
#define COORDINATE_GAMELIST_TOP_RIGHT_Y COORDINATE_GAMELIST_TOP_LEFT_Y
/*this is gamelist bottomleft*/
#define COORDINATE_GAMELIST_BOTTOM_LEFT_X COORDINATE_GAMELIST_TOP_LEFT_X
#define COORDINATE_GAMELIST_BOTTOM_LEFT_Y COORDINATE_GAMELIST_TOP_LEFT_Y+GAMELIST_HEIGHT
/*this is gamelist bottomright*/
#define COORDINATE_GAMELIST_BOTTOM_RIGHT_X COORDINATE_GAMELIST_TOP_LEFT_X+GAMELIST_WIDTH
#define COORDINATE_GAMELIST_BOTTOM_RIGHT_Y COORDINATE_GAMELIST_TOP_LEFT_Y+GAMELIST_HEIGHT


/*we need't calculate the setting area,cuz it's overlap with the side two area*/
/*this is setting area*/

/*this is setting_area size*/
#define SETTING_AREA_WIDTH LEFT_MIDDLE_MARGIN*2+OUTERMOST_BORDER_WIDTH
#define SETTING_AREA_HEIGHT TOP_MIDDLE_MARGIN
/*this is setting_area left*/

/*this is setting_area bottomleft*/
#define COORDINATE_SETTING_AREA_BOTTOM_LEFT_X COORDINATE_GAMELIST_TOP_RIGHT_X
#define COORDINATE_SETTING_AREA_BOTTOM_LEFT_Y COORDINATE_GAMELIST_TOP_RIGHT_Y+TOP_MIDDLE_MARGIN
/*this is setting_area bottomright*/
#define COORDINATE_SETTING_AREA_BOTTOM_RIGHT_X COORDINATE_SETTING_AREA_BOTTOM_LEFT_X+SETTING_AREA_WIDTH
#define COORDINATE_SETTING_AREA_BOTTOM_RIGHT_Y COORDINATE_SETTING_AREA_BOTTOM_LEFT_Y

/*this is the right scorelist area*/
#define SCORELIST_WIDTH GAMELIST_WIDTH
#define SCORELIST_HEIGHT GAMELIST_HEIGHT

/*this is right scorelist topleft*/
#define COORDINATE_SCORELIST_TOP_LEFT_X COORDINATE_GAMELIST_TOP_LEFT_X+GAMELIST_WIDTH+SETTING_AREA_WIDTH
#define COORDINATE_SCORELIST_TOP_LEFT_Y COORDINATE_GAMELIST_TOP_LEFT_Y
/*this is right scorelist topright*/
#define COORDINATE_SCORELIST_TOP_RIGHT_X COORDINATE_SCORELIST_TOP_LEFT_X+SCORELIST_WIDTH
#define COORDINATE_SCORELIST_TOP_RIGHT_Y COORDINATE_SCORELIST_TOP_LEFT_Y
/*this is right scorelist bottomleft*/
#define COORDINATE_SCORELIST_BOTTOM_LEFT_X COORDINATE_SCORELIST_TOP_LEFT_X
#define COORDINATE_SCORELIST_BOTTOM_LEFT_Y COORDINATE_SCORELIST_TOP_LEFT_Y+SCORELIST_HEIGHT
/*this is right scorelist bottomright*/
#define COORDINATE_SCORELIST_BOTTOM_RIGHT_X COORDINATE_SCORELIST_TOP_LEFT_X+SCORELIST_WIDTH
#define COORDINATE_SCORELIST_BOTTOM_RIGHT_Y COORDINATE_SCORELIST_TOP_LEFT_Y+SCORELIST_HEIGHT

// void print_horizontal_line(int x1,int x2,int y);
// void print_vertical_line(int x,int y1,int y2);

/*all the scope is various rectangle, that's all*/
/*biggest one*/
#define BIGGEST_RECTANGLE_COORDINATE_X COORDINATE_GAMELIST_TOP_LEFT_X
#define BIGGEST_RECTANGLE_COORDINATE_Y COORDINATE_GAMELIST_TOP_LEFT_Y
#define BIGGEST_RECTANGLE_WIDTH GAMELIST_WIDTH*2+SETTING_AREA_WIDTH
#define BIGGEST_RECTANGLE_HEIGHT GAMELIST_HEIGHT

/*setting one*/
#define SETTING_RECTANGLE_COORDINATE_X COORDINATE_MIDDLE_TOP_LEFT_X
#define SETTING_RECTANGLE_COORDINATE_Y COORDINATE_GAMELIST_TOP_RIGHT_Y
#define SETTING_RECTANGLE_WIDTH SETTING_AREA_WIDTH
#define SETTING_RECTANGLE_HEIGHT SETTING_AREA_HEIGHT

/*last UNDER_MIDDLE under the outermost*/
#define UNDER_MIDDLE_RECTANGLE_COORDINATE_X COORDINATE_MIDDLE_TOP_LEFT_X
#define UNDER_MIDDLE_RECTANGLE_COORDINATE_Y COORDINATE_GAMELIST_TOP_LEFT_Y
#define UNDER_MIDDLE_RECTANGLE_WIDTH OUTERMOST_BORDER_WIDTH
#define UNDER_MIDDLE_RECTANGLE_HEIGHT GAMELIST_HEIGHT

/*this is gamelist mode choose module*/


#define CHOOSE_MODULE_RECTANGLE_COORDINATE_X COORDINATE_GAMELIST_TOP_LEFT_X
#define CHOOSE_MODULE_RECTANGLE_COORDINATE_Y COORDINATE_GAMELIST_TOP_LEFT_Y
#define CHOOSE_MODULE_RECTANGLE_WIDTH GAMELIST_WIDTH+LEFT_MIDDLE_MARGIN+1
#define CHOOSE_MODULE_RECTANGLE_HEIGHT GAMELIST_HEIGHT

/*this is t or f block*/
#define COORDINATE_T_X OUTERMOST_BORDER_X + OUTERMOST_BORDER_WIDTH / 4 - (4+1)/ 2
#define COORDINATE_T_Y OUTERMOST_BORDER_Y + OUTERMOST_BORDER_HEIGHT + T_F_MEANING_MARGIN + MEANING_MIDDLE_MARGIN + MARGIN_WORD_BORDER_Y
#define COORDINATE_F_X OUTERMOST_BORDER_X + OUTERMOST_BORDER_WIDTH / 4 - (4+1)/2 + OUTERMOST_BORDER_WIDTH / 2
#define COORDINATE_F_Y COORDINATE_T_Y


/*this is under develop tips*/
#define UNDER_DEVELOP_TIPS "This feature is under development."

/*this is setting develop tips*/
#define SETTING_DEVELOP_TIPS "Setting Area..."

/*this is game mode tips*/
#define GAME_MODE_TIPS "Game Mode"

/*this is score list tips*/
#define SCORE_LIST_TIPS "Score List"


_Rectangle * init_outermost_rectangle();
_Rectangle * init_biggest_rectangle();
_Rectangle * init_setting_rectangle();
_Rectangle * init_under_middle_rectangle();
_Rectangle * init_selected_mode_choose_mudule_to_red();


#endif /* OUTERMOST_RECTANGLE_H_ */