#ifndef WORD_RECTANGLE_H_
#define WORD_RECTANGLE_H_

// #define WORD_BORDER_CORNER '+'
// #define WORD_BORDER_VERTICAL '|'
// #define WORD_BORDER_HORIZONTAL '-'

#define WORD_BORDER_ALL_EMPTY ' '
#define WORD_BORDER_CORNER WORD_BORDER_ALL_EMPTY
#define WORD_BORDER_VERTICAL WORD_BORDER_ALL_EMPTY
#define WORD_BORDER_HORIZONTAL WORD_BORDER_ALL_EMPTY


#define T_F_BORDER_DOT '.'
#define T_F_BORDER_DOT_EMPTY ' '
#define T_F_BORDER_CORNER T_F_BORDER_DOT
#define T_F_BORDER_VERTICAL '|'
#define T_F_BORDER_HORIZONTAL '-'

#endif /* WORD_RECTANGLE_H_ */